### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by RobLoach** [pattern-lab/patternengine-node-twig#1]
Need any help with getting this up and running?

**Comment by bmuenzenmeyer** [comment]
@geoffp do you know the status of your brnach> can it be pushed to a dev branch here?

**Comment by geoffp** [comment]
Yes! I have to port to PL2. I'll try to find some time to do this soon.

**Comment by geoffp** [comment]
@RobLoach okay, there's the preliminary port of whatever we had in PL1.X for you to play around with. It passes the unit tests, for whatever that's worth, though I can't personally guarantee that it will work for any real work.

I'm hoping you'll do that. ;)
